export enum PlatformType {
  ANDROID = 'ANDROID',
  WEB = 'WEB',
  IOS = 'IOS',
  SERVER = 'SERVER',
  NODE = 'NODE',
  REACT = 'REACT',
  ANGULAR = 'ANGULAR',
  VUE = 'VUE',
  SVELTE = 'SVELTE',
  SPRING = 'SPRING',
  GO = 'GO',
  JAVA = 'JAVA',
  C = 'C',
  CPP = 'CPP',
  JS = 'JS',
  PYTHON = 'PYTHON',
  RUST = 'RUST',
  RUBY = 'RUBY',
  LARAVEL = 'LARAVEL',
  PHP = 'PHP',
  EXPRESS = 'EXPRESS',
  NEST = 'NEST',
  CS = 'CS',
  OTHER = 'OTHER'
}