name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the project! Thank you for creating your first issue. We're here to help, so feel free to ask any questions or share any thoughts you have. Happy collaborating!"
        pr-message: "Hello and welcome! Thank you for your first pull request. Your contribution is appreciated. If you need any guidance or assistance, don't hesitate to reach out. Happy coding!"
